# Generated by Django 2.2.5 on 2019-09-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='toll_fee',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='toll_fee',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=10, null=True),
        ),
    ]
