# Generated by Django 2.2.5 on 2019-09-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0002_auto_20190921_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='fax',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='provider',
            name='zip',
            field=models.CharField(max_length=5),
        ),
    ]
