# Generated by Django 2.2.5 on 2019-09-23 15:30

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('provider', '0003_auto_20190921_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('mobile_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('office_phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('fax_number', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('toll_fee', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='provider',
            name='fax',
            field=phone_field.models.PhoneField(blank=True, default='000000000', help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='provider',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, default='000000000', help_text='Contact phone number', max_length=31),
        ),
    ]
